- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  tasks:

    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest
 
    - name: Create document root for domain configured in host variable
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'
 
    - name: Copy your index file
      template:
        src: "files/index-template.html"
        dest: "/var/www/{{ http_host }}/index.html"
 
    - name: Set up virtuahHost
      template:
        src: "files/apache-template.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Disable default Apache website
      command: a2dissite 000-default.conf

    - name: Delete 000-default.conf
      shell: rm -rf /etc/apache2/sites-available/000-default.conf

    - name: Enable site
      command: a2ensite {{ http_conf }}
      notify: restart-apache

    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow

    - name: "UFW firewall allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
 
    - name: "UFW firewall allow port"
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:  "{{ ufw_port }}" 

    - name: Install Repository
      apt: 
        name:  software-properties-common
        state:  latest

    - name: Add php repository
      apt_repository:
        repo: 'ppa:ondrej/php'

    - name: Install PHP and required modules
      apt:
        name: 
          - php8.1
          - php8.1-fpm
          - libapache2-mod-php
          - libapache2-mod-fcgid
          - php8.1-mysql
          - php8.1-curl
          - php8.1-gd
          - php8.1-zip
          - php8.1-mbstring
          - php8.1-xml
        update_cache: yes
        state: present

    - name: Enable PHP-FPM with Apache
      command: "{{ item }}"
      with_items:
        - a2enmod proxy_fcgi setenvif
        - a2enconf php8.1-fpm
      notify: restart-apache

    - name: Start & Enable php-fpm
      service: 
        name: php8.1-fpm
        state: started
        enabled: yes
      notify: restart_php-fpm  

    - name: Install unzip
      apt: 
        name: unzip
        state: latest

    - name: Download php-composer
      get_url:
        url: https://getcomposer.org/installer
        dest: /tmp/installer

    - name: install composer
      shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
      args:
        creates: /usr/local/bin/composer

    - name: rename composer.phar to composer
      shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer
      args:
        creates: /usr/local/bin/composer

    - name: make composer executable
      file: 
        path: /usr/local/bin/composer
        mode: a+x
        state: file

  handlers:
    - name: restart-apache
      service:
        name: apache2
        state: restarted

    - name: restart_php-fpm
      service:
        name: php8.1-fpm
        state: restarted