- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  tasks:

    - name: extract archive
      unarchive:
        src: https://files.phpmyadmin.net/phpMyAdmin/5.2.1/phpMyAdmin-5.2.1-all-languages.zip
        dest: /var/www/html/phpmyadmin/
        remote_src: true
        validate_certs: no

    - name: Move file
      file:
        src: /var/www/html/phpmyadmin/phpMyAdmin-5.2.1-all-languages/*
        dest: /var/www/html/phpmyadmin/
        state: link

    - name: Rename File 
      file:
        src: /var/www/html/phpmyadmin/config.sample.inc.php
        dest: /var/www/html/phpmyadmin/config.inc.php
        state: link