- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  tasks:

    - name: Creat directory phpmyadmin
      file:
        path: /var/www/html/phpmyadmin
        state: directory

    - name: Download PhpMyadmin from website
      get_url:
        url:  https://files.phpmyadmin.net/phpMyAdmin/5.2.1/phpMyAdmin-5.2.1-all-languages.zip
        dest: /var/www/html/phpmyadmin/phpMyAdmin-5.2.1-all-languages.zip
        mode: '0440'

    - name: Unzip file Phpmyadmin.zip, Move file and rename file configure
      command: "{{ item }}"
      with_items:
        - unzip /var/www/html/phpmyadmin/phpMyAdmin-5.2.1-all-languages.zip
        - mv /var/www/html/phpmyadmin/phpMyAdmin-5.2.1-all-languages/* /var/www/html/phpmyadmin/
        - mv /var/www/html/phpmyadmin/config.sample.inc.php /var/www/html/phpmyadmin/config.inc.php
      changed_when: False