- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  tasks:

    - name: Set up phpmyadmin directory
      template:
        src: "files/directory.conf"
        dest: "/etc/apache2/sites-enabled/directory.conf"
