- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install python3-regex package
      apt:
        name: python3-regex
        state: present

    - name: Search and edit file config.inc.php
      replace:
        path: /var/www/html/phpmyadmin/config.inc.php
        regexp: 'localhost'
        replace: '192.168.254.134'
