- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  tasks:

    - name: extract archive
      unarchive:
        src: /var/www/html/phpmyadmin/phpMyAdmin-5.2.1-all-languages.zip
        dest: /var/www/html/phpmyadmin/
