- name: Ansible Playbook to Install and Setup Apache on Ubuntu
  hosts: stagingsrvgrp
  become: yes
  tasks:

    - name: Search and edit file config.inc.php
      lineinfile:
        path: /var/www/html/phpmyadmin/config.inc.php
        regexp: "$cfg['Servers'][$i]['host'] = 'localhost';"
        line: "$cfg['Servers'][$i]['host'] = '192.168.254.134';"
