---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install MySQL Software Repo
      yum:
        name: http://repo.mysql.com/mysql80-community-release-el7-5.noarch.rpm
        state: present

    - name: Install MySQL Database
      yum: name=mysql-server state=present
      
    - name: Install MySQL-python
      yum: name=MySQL-python state=present   

    - name: Start & Enable MySQL Server to start on boot
      service: 
        name: mysqld
        state: started
        enabled: yes

    - shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}';
      register: result
    -  set_fact:
        mysql_root_pw: "{{ result.stdout }}"

    - name: use "mysql_secure_installation" for Fresh MySQL Installation
      mysql_secure_installation:
        login_password: "{{ result.stdout }}"
        new_password: 'ITP@144BD'
        user: root
        login_host: localhost
        hosts: ['localhost', '127.0.0.1', '::1']
        change_root_password: false
        remove_anonymous_user: true
        disallow_root_login_remotely: true
        remove_test_db: true
      register: secure