---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  vars:
    mysql_root_pw: Khoi@8888
    mysql_pass: Thien@9999
  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install EPEL repo.
      yum:
        name: epel-release
        state: present

    - name: Install python-pip.
      yum:
        name: python-pip
        state: present

    - name: install pexpect
      pip:
        name: pexpect        

    - name: Install MySQL Software Repo
      yum:
        name: http://repo.mysql.com/mysql80-community-release-el7-5.noarch.rpm
        state: present

    - name: Install MySQL Database
      yum: name=mysql-server state=present
      
    - name: Install MySQL-python
      yum: name=MySQL-python state=present   

    - name: Start & Enable MySQL Server to start on boot !
      service: 
        name: mysqld
        state: started
        enabled: yes

    - name: Set MySQL root Password
      mysql_user:
        login_host: 'localhost'
        login_user: 'root'
        login_password: '{{ mysql_root_pw }}'
        name: 'root'
        password: '{{ mysql_pass }}'
        state: present         

