---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  vars:
    mysql_root_user: root
    mysql_root_password: Thien@8888
  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install EPEL repo.
      yum:
        name: epel-release
        state: present

    - name: Install python-pip.
      yum:
        name: python-pip
        state: present

    - name: install pexpect
      pip:
        name: pexpect        

    - name: Install MySQL Software Repo
      yum:
        name: http://repo.mysql.com/mysql80-community-release-el7-5.noarch.rpm
        state: present

    - name: Install MySQL Database
      yum: name=mysql-server state=present
      
    - name: Install MySQL-python
      yum: name=MySQL-python state=present   

    - name: Start & Enable MySQL Server to start on boot !
      service: 
        name: mysqld
        state: started
        enabled: yes

    - name: Get MySQL temporary root password from log
      shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      changed_when: false
      register: mysql_temp_pw

    - name: Set MySQL root password as a fact
      set_fact:
        mysql_root_pw: "{{ mysql_temp_pw.stdout }}"

    - name: Change root password using expect
      expect:
        command: mysqladmin -u {{ mysql_root_user }} password "{{ mysql_root_pw }}"
        responses:
          Enter password: "{{ mysql_root_password }}"           

