---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  vars:
    mysql_root_password: Khoi@8888
  tasks:

    - name: Remove anonymous users
      command: mysql --user root --password={{ mysql_root_password }} --execute="{{ item }};"
      with_items:
        - DELETE FROM mysql.user WHERE User=''
      changed_when: False    
