---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install MySQL Software Repo
      yum:
        name: http://repo.mysql.com/mysql80-community-release-el7-5.noarch.rpm
        state: present

    - name: Install MySQL Database
      yum: name=mysql-server state=present
      
    - name: Install MySQL-python
      yum: name=MySQL-python state=present   

    - name: Start & Enable MySQL Server to start on boot
      service: 
        name: mysqld
        state: started
        enabled: yes

    - shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}';
      register: result
    -  set_fact:
        mysql_root_pw: "{{ result.stdout }}"

    - name: Run mysql_secure_installation for fresh installation
      expect:
        command: mysql_secure_installation
        responses:
          'Enter current password for root (enter for none):': ''
          'Set root password? [Y/n]': 'Y'
          'New password:': 'ITP@144BD'
          'Re-enter new password:': 'ITP@144BD'
          'Remove anonymous users? [Y/n]': 'Y'
          'Disallow root login remotely? [Y/n]': 'Y'
          'Remove test database and access to it? [Y/n]': 'Y'
          'Reload privilege tables now? [Y/n]': 'Y'