---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  tasks:
    - name: Upgrade all packages
      name: '*'
      state: latest
      
    - name: Install MySQL Software Repo
      yum:
        name: http://dev.mysql.com/get/mysql80-community-release-el7-5.noarch.rpm
        state: present

    - name: Install MySQL Database
      yum: 
        name: mysql-server
        state: present

    - name: Start & Enable MySQL Server to start on boot
      service: 
        name: mysqld
        state: started
        enabled: yes

    - shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}';
      register: result
    -  set_fact:
        mysql_root_pw: "{{ result.stdout }}"

    - stat: path=/root/.my.cnf
      register: sym
    - set_fact: mysql_root_pw="ITP@144BD"
      when: sym.stat.exists == True

    - name: install .my.cnf with credentials
      template: src=my.cnf.j2 dest=/root/.my.cnf
                mode=0400
      tags: my_cnf

    - name: Set the root password for MySQL Database
      command:  mysql -u root --connect-expired-password --execute="SET PASSWORD = PASSWORD('ITP@144BD');"
        
    -  set_fact:
        mysql_root_pw: "ITP@144BD"

    - name: install .my.cnf with credentials
      template: src=my.cnf.j2 dest=/root/.my.cnf
                mode=0400
      tags: my_cnf

    - name: Create the database for website
      mysql_db: name=test state=present

    - name: Create the Application user for the database
      mysql_user: name=admin password=ITP@144BD priv='*.*:ALL' host='%' state=present
        
    - name: Enable the firewall port for MySQL
      firewalld: port=3306/tcp permanent=true state=enabled immediate=yes