---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  vars:
    mysql_root_password: Khoi@8888
  tasks:

    - name: Run mysql_secure_installation
      command: mysql --user root --password={{ mysql_root_password }} --execute="{{ item }};"
      with_items:
        - DELETE FROM mysql.user WHERE User=''
        - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
        - DROP DATABASE IF EXISTS test
        - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
        - FLUSH PRIVILEGES
      changed_when: False    