---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install EPEL repo.
      yum:
        name: epel-release
        state: present

    - name: Install python-pip.
      yum:
        name: python-pip
        state: present

    - name: install pexpect
      pip:
        name: pexpect        

    - name: Install MySQL Software Repo
      yum:
        name: http://repo.mysql.com/mysql80-community-release-el7-5.noarch.rpm
        state: present

    - name: Install MySQL Database
      yum: name=mysql-server state=present
      
    - name: Install MySQL-python
      yum: name=MySQL-python state=present   

    - name: Start & Enable MySQL Server to start on boot !
      service: 
        name: mysqld
        state: started
        enabled: yes

    - name: Extract MySQL root password from log file !
      shell: grep 'password' /var/log/mysqld.log | awk '{print $NF}'
      register: mysql_password

    - name: Configure MySQL with extracted password !
      expect:
        command: mysql_secure_installation
        responses:
          'Enter password for user root:': '{{ mysql_password.stdout }}'
          'New password:': 'Cntt@8888'
          'Re-enter new password:': 'Cntt@8888'
          'Change the password for root ? ((Press y|Y for Yes, any other key for No) :': 'n'
          'Remove anonymous users? (Press y|Y for Yes, any other key for No) :': 'Y'
          'Disallow root login remotely? (Press y|Y for Yes, any other key for No) :': 'Y'
          'Remove test database and access to it? (Press y|Y for Yes, any other key for No) :': 'Y'
          'Reload privilege tables now? (Press y|Y for Yes, any other key for No) :': 'Y'