---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  vars:
    mysql_root_password: Khoi@8888
  tasks:

    - name: Remove anonymous user accounts
      mysql_user:
        name: ''
        host_all: true
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: absent
