---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  tasks:

    - name: Update CentOS with skip-broken option
      yum:
        name: '*'
        state: latest
        skip_broken: yes

    - name: Verify RPM package integrity
      shell: rpm -Va --nofiles --nodigest

 