---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  vars:
    mysql_root_pass: Khoi@8888
  tasks:

    - name: Removes anonymous user account for localhost
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_pass }}"
        name: ''
        host: localhost
        state: absent
        login_unix_socket: /run/mysqld/mysqld.sock
