---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  tasks:

    - name: Configure MySQL repository
      yum_repository:
        name: mysql
        description: MySQL Community Server
        baseurl: http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
        gpgcheck: yes
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-mysql
        enabled: yes

    - name: Update all packages
      yum:
        name: '*'
        state: latest

 