---
- name: MySQL Server Setup
  hosts: dbsrvgrp
  become: yes
  tasks:

    - name: Update all packages
      yum:
        name: '*'
        state: latest

    - name: Install EPEL repo.
      yum:
        name: epel-release
        state: present

    - name: Install python-pip.
      yum:
        name: python-pip
        state: present

    - name: install pexpect
      pip:
        name: pexpect        

    - name: Install MySQL Software Repo
      yum:
        name: http://repo.mysql.com/mysql80-community-release-el7-5.noarch.rpm
        state: present

    - name: Install MySQL Database
      yum: name=mysql-server state=present
      
    - name: Install MySQL-python
      yum: name=MySQL-python state=present   

    - name: Start & Enable MySQL Server to start on boot
      service: 
        name: mysqld
        state: started
        enabled: yes

    - name: Extract MySQL root password from log file
      shell: grep 'password' /var/log/mysqld.log | awk '{print $NF}'
      register: mysql_password

    - name: Configure MySQL with extracted password
      expect:
        command: mysql_secure_installation
        responses:
          'Enter current password for root (enter for none):': '{{ mysql_password.stdout }}'
          'Set root password? [Y/n]': 'Y'
          'New password:': 'ITP@144BD'
          'Re-enter new password:': 'ITP@144BD'
          'Change the password for root ? [Y/n]': 'n'
          'Remove anonymous users? [Y/n]': 'Y'
          'Disallow root login remotely? [Y/n]': 'Y'
          'Remove test database and access to it? [Y/n]': 'Y'
          'Reload privilege tables now? [Y/n]': 'Y'