
- name: Setup Apache2 & Deploy Artifact
  hosts: appsrvgrp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
  tasks:
    - name: Download latest weblab.tgz from nexus
      get_url:
        url: "http://{{USER}}:{{PASS}}@{{nexusip}}:8081/repository/{{reponame}}/{{artifactname}}/{{hyphen}}/{{weblab_version}}"
        dest: "/tmp/weblabapp-{{weblab_version}}"
      register: tgzdeploy
      tags:
       - deploy

    - stat:
        path: /var/www/weblab.local/ROOT
      register: artifact_stat
      tags:
        - deploy

    - name: Stop Apache
      service:
        name:
          - apache2
          - php8.1-fpm
        state: stopped
      tags:
        - deploy

    - name: Try Backup and Deploy
      block:
      - name: Archive ROOT dir with timestamp
        archive:
          path: /var/www/weblab.local/ROOT
          dest: "/opt/ROOT_{{timestamp}}.tgz"
        when: artifact_stat.stat.exists
        register: archive_info
        tags:
          - deploy

      - name: copy ROOT dir with old_ROOT name
        shell: cp -r ROOT old_ROOT
        args:
          chdir: /var/www/weblab.local/

      - name: Delete current artifact
        file:
          path: "{{item}}"
          state: absent
        when: archive_info.changed
        loop:
          - /var/www/weblab.local/ROOT
          - /var/www/weblab.local/ROOT.tgz
        tags:
          - deploy

      - name: Try deploy artifact else restore from previos old_ROOT
        block:
         - name: Deploy weblab artifact
           copy:
             src: "/tmp/weblabapp-{{weblab_version}}"
             dest: /var/www/weblab.local/ROOT.tgz
             remote_src: yes
           register: deploy_info
           tags:
            - deploy
        rescue:
          - shell: cp -r old_ROOT ROOT
            args:
              chdir: /var/www/weblab.local/

      rescue:
       - name: Start Apache2 php8.1-fpm
         service:
          name: 
		        -  apache2
            -  php8.1-fpm
          state: started

    - name: Start Apache2 php8.1-fpm
      service:
        name: 
		      -  apache2
		      -  php8.1-fpm		  
        state: started
      when: deploy_info.changed
      tags:
        - deploy

    - name: Wait until ROOT.tgz is extracted to ROOT directory
      wait_for:
        path: /var/www/weblab.local/ROOT
      tags:
       - deploy


  handlers:
   - name: Restart Apache2
     service:
      name: Apache2
      state: restarted
