
- name: Setup Apache2 & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  sudo: yes
  tasks:

    - name: Install nvm
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    - name: Setup .profile
      lineinfile:
        path: ~/.profile
        line: source ~/.nvm/nvm.sh
        create: yes

    - name: Install node
      shell: |
        nvm install {{item}}
      args:
        executable: /bin/bash
        chdir: "$HOME"
        creates: "$HOME/.nvm/versions/node/v{{item}}"
      loop:
        - 18.16.0

    - name: npm install
      shell: npm install --force
      args:
        chdir: /var/www/weblab.local/public_html

    - name: Run Build package
      shell: npm run build
      args:
        chdir: /var/www/weblab.local/public_html

  handlers:
   - name: Restart Apache2
     service:
      name: Apache2
      state: restarted
