
- name: Setup Apache2 & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  vars:
    timestamp: "{{ansible_date_time.date}}_{{ansible_date_time.hour}}_{{ansible_date_time.minute}}"
  tasks:
    
    - name: Install curl
      apt:
        name: curl
        state: present

    - name: Download and run Node.js setup script
      shell: curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -

    - name: Instal Node.js
      apt:
        name: nodejs
        state: present
		


