
- name: Setup Apache2 & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  tasks:

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required get_md5=no

    - name: Reboot the box if kernel updated
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Install latest version of Apache
      apt: name=apache2 update_cache=yes state=latest
 
    - name: Create document root for domain configured in host variable
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Creat directory BK
      file:
        path: "/var/www/{{ http_host }}/BK"
        state: directory

    - name: Creat directory public_html
      file:
        path: "/var/www/{{ http_host }}/public_html"
        state: directory    

    - name: Set up virtuahHost
      template:
        src: "files/apache-template.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"

    - name: Disable default Apache website
      command: a2dissite 000-default.conf

    - name: Remove default apache vhost config from sites-enabled
      file: name=/etc/apache2/sites-enabled/000-default.conf state=absent

    - name: Enable site
      command: a2ensite {{ http_conf }}
      notify: restart-apache

    - name: Allow everything and enable UFW
      ufw:
        state: enabled
        policy: allow

    - name: "UFW firewall allow HTTP on port {{ http_port }}"
      ufw:
        rule: allow
        port: "{{ http_port }}"
        proto: tcp
 
    - name: "UFW firewall allow port"
      ufw:
        rule: allow
        port: "{{ item }}"
        proto: tcp
      loop:  "{{ ufw_port }}" 
       
    - name: change directory and install dependencies
      command: chdir=/var/www/weblab.local/public_html npm install --force

