
- name: Setup Apache2 & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  tasks:

#    - name: change directory and install dependencies
#      command: chdir=/var/www/weblab.local/public_html npm install --force

    - name: change directory and install dependencies
      command: chdir=/var/www/weblab.local/public_html npm run build