
- name: Setup Apache2 & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  tasks:
 
    - name: install all dependencies
      shell: npm install --force
        chdir: /var/www/weblab.local/public_html

