
- name: Setup Apache2 & Deploy Artifact
  hosts: stagingsrvgrp
  become: yes
  tasks:
 
   - name: Install project dependencies
     command: sudo npm install --force
     args:
       chdir: /var/www/weblab.local/public_html

